# Generated by Django 4.0.6 on 2022-09-04 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='updated',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='create_time',
            field=models.CharField(default=2000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlepost',
            name='favors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='passage_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
