# Generated by Django 4.0.6 on 2022-09-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlepost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='pre_id',
            field=models.CharField(default='UnKnown', max_length=20),
        ),
    ]
