# Generated by Django 4.0.6 on 2022-09-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_articlepost_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.DeleteModel(
            name='ArticleColumn',
        ),
    ]
