# Generated by Django 4.0.6 on 2022-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articlepost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='tag',
            field=models.CharField(default='notag', max_length=10),
        ),
    ]
