# Generated by Django 4.0.6 on 2022-09-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_articlepost_abs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-create_time',)},
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='created',
        ),
    ]
