# Generated by Django 4.0.6 on 2022-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_articlepost_options_remove_articlepost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
