# Generated by Django 4.0.6 on 2022-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_articlepost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='author_articles',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='author_followers',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='author_img_src',
            field=models.CharField(default='/media/user_img/default.png', max_length=50),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='author_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='author_url',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
